name: clustering_analysis_env
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.9
  - numpy
  - pandas
  - biopython
  - scikit-learn
  - matplotlib
  - scipy
  - hdbscan
  - pip
  - pip:
    - joblib


# To create this environment, use the following command:
# conda env create -f environment_cluster.yml

# Also you need to have clustio installed on your system for running the clustalw command.
# To install clustio, use the following command:
# sudo apt install clustio (for linux)
